# Generated by Django 4.2 on 2024-09-27 08:24

from django.db import migrations, models
import django_jalali.db.models
import gold_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان محصول')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('product_img', models.ImageField(upload_to=gold_page.models.products_image_path, verbose_name='تصویر')),
                ('show_slider', models.BooleanField(default=False, verbose_name='نمایش در اسلایدر')),
                ('create_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_date', django_jalali.db.models.jDateField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
